name: bot1

on:
  schedule:
    - cron: "*/1 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: send message
        uses: dawid66/action-send-mail@v3
        with:
          server_adress: smtp.gmail.com
          server_port: 465
          username: hafeyom977@datingel.com
          subject: "touch some grass"
          to: rurdujerki@gufum.com
