name: bot1

on:
  schedule:
    - cron: "*/1 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Install sendmail
        run: sudo apt-get install -y sendmail

      - name: Send Raw Email
        run: |
          echo -e "Subject: Touch some grass\n\nThis is the email content." | sendmail -v hafeyom977@datingel.com

