name: Send Email with Multiple Attachments

on:
  push:
    branches:
      - main  # Change to your branch if needed

jobs:
  send_email:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Send Email
        uses: dawidd6/action-send-mail@v4
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.GMAIL_USERNAME }}  # Your Gmail address
          password: ${{ secrets.GMAIL_PASSWORD }}  # Your Gmail app password
          subject: "Automated Email with Multiple Attachments"
          body: "Hello,\n\nThis is an automated email sent from GitHub Actions with multiple attachments."
          to: "recipient@example.com"  # Change to the recipient's email address
          from: "${{ secrets.GMAIL_USERNAME }}"  # Sender's email address
          attachments: "path/to/your/file1.pdf,path/to/your/file2.png,path/to/your/file3.docx"  # List of attachments separated by commas
