name: Send Email with Attachment

on:
  push:
    branches:
      - main  # Change to your branch if needed

jobs:
  send_email:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Send Email
        uses: dawidd6/action-send-mail@v4
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: newmailforproject@freesourcecodes.com # Your Gmail address
          password: new147  # Your Gmail app password
          subject: "Automated Email with Attachment"
          body: "Hello,\n\nThis is an automated email sent from GitHub Actions with an attachment."
          to: "recipient@example.com"  # Change to the recipient's email address
          from: "${{ secrets.MAIL }}"  # Sender's email address
          attachments: "touch some grass.png"  # Change this to the path of your attachment
